"""empty message

Revision ID: 087fdc3f5342
Revises: 
Create Date: 2023-09-01 12:27:26.112302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087fdc3f5342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Email', sa.String(length=320), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password', sa.String(length=120), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('Face_path', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
