"""empty message

Revision ID: a957ffbd973b
Revises: 
Create Date: 2023-09-26 16:40:55.734009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a957ffbd973b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Email', sa.String(length=320), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=True),
    sa.Column('Password', sa.String(length=120), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('Face_path', sa.String(length=300), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Status'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('Raspberry',
    sa.Column('R_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owned', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owned'], ['user.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('R_ID'),
    sa.UniqueConstraint('Status')
    )
    op.create_table('history',
    sa.Column('H_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('U_ID', sa.Integer(), nullable=True),
    sa.Column('Login_Time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['U_ID'], ['user.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('H_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('Raspberry')
    op.drop_table('user')
    # ### end Alembic commands ###
