"""empty message

Revision ID: d861bfee4104
Revises: 087fdc3f5342
Create Date: 2023-09-04 17:38:11.950016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd861bfee4104'
down_revision = '087fdc3f5342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['Username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('Username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
